version: "3.3"
services: 
  app-test:
    environment:
        - FLASK_APP=flaskr
        - FLASK_ENV=development
        - FLASK_RUN_PORT=5000
    build: .  
    command: flask run --host=0.0.0.0
    ports: 
      - "5000:5000"
    volumes:
      - .:/usr/api-test

